### ISSUE TITLE
Kryptic names of the output files

### ISSUE THREAD

**Issue by GregFie** [EventStudyTools/api-wrapper.r#9]
Dear all,

when I use the API, the resulting files have kryptic names which are not assignable to the original files.

e.g. the CAAR File calls: 0a2c0c701a75f2e0cfe2363ee1be76ba668c9a31eb0ddb0c2fc7a819029e1021

I've got no idea why this happens and how to solve it. Unfortunately this happens since several days.
Strangely, the names differ even when I run the event study with the same data - e.g. the example data. 

Does anybody know why this happens and how to solve it?

Best regards,

Gregor Fiedler

**Comment by sipemu** [comment]
Hello Mr. Fiedler,

please install the actual github version 0.36. I fixed this issue some days ago.

Best,
Simon Müller

**Comment by GregFie** [comment]
Dear Dr. Mueller,

I tried you're advice. Unfortunately it still doesn't work. I reinstalled the package several times. But without any success. By the way, there is no 0.36. version.

I would appreciate it a lot if you might help me. What you mean by: "install the github version 0.36"?

Have a nice evening.

Best regards,

Gregor Fiedler
